[2024-08-21T22:32:35.724+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T22:32:35.740+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_spark_tasks.postgres_analysis manual__2024-08-21T22:12:10.549926+00:00 [queued]>
[2024-08-21T22:32:35.746+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_spark_tasks.postgres_analysis manual__2024-08-21T22:12:10.549926+00:00 [queued]>
[2024-08-21T22:32:35.747+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 3
[2024-08-21T22:32:35.757+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): postgres_analysis> on 2024-08-21 22:12:10.549926+00:00
[2024-08-21T22:32:35.764+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=782) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-21T22:32:35.765+0000] {standard_task_runner.py:72} INFO - Started process 784 to run task
[2024-08-21T22:32:35.766+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_spark_tasks', 'postgres_analysis', 'manual__2024-08-21T22:12:10.549926+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp4z_zzzle']
[2024-08-21T22:32:35.766+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask postgres_analysis
[2024-08-21T22:32:35.799+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_spark_tasks.postgres_analysis manual__2024-08-21T22:12:10.549926+00:00 [running]> on host 2b775d69f181
[2024-08-21T22:32:35.862+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_spark_tasks' AIRFLOW_CTX_TASK_ID='postgres_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T22:12:10.549926+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T22:12:10.549926+00:00'
[2024-08-21T22:32:35.863+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-21T22:32:35.863+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-21T22:32:35.864+0000] {logging_mixin.py:190} INFO - Current task name:postgres_analysis state:running start_date:2024-08-21 22:32:35.740408+00:00
[2024-08-21T22:32:35.864+0000] {logging_mixin.py:190} INFO - Dag name:docker_spark_tasks and current dag run status:running
[2024-08-21T22:32:35.864+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T22:32:35.864+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T22:32:35.865+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec node-master /home/spark/src/spark/submit.sh postgres_analysis.py']
[2024-08-21T22:32:35.877+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T22:32:37.829+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/spark/spark-3.5.1-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-21T22:32:37.914+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/spark/.ivy2/cache
[2024-08-21T22:32:37.914+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/spark/.ivy2/jars
[2024-08-21T22:32:37.919+0000] {subprocess.py:93} INFO - org.postgresql#postgresql added as a dependency
[2024-08-21T22:32:37.920+0000] {subprocess.py:93} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2024-08-21T22:32:37.920+0000] {subprocess.py:93} INFO - org.mongodb.spark#mongo-spark-connector_2.12 added as a dependency
[2024-08-21T22:32:37.920+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-85246f7a-ce89-48e6-8695-f3658629f852;1.0
[2024-08-21T22:32:37.920+0000] {subprocess.py:93} INFO - 	confs: [default]
[2024-08-21T22:32:38.017+0000] {subprocess.py:93} INFO - 	found org.postgresql#postgresql;42.5.4 in central
[2024-08-21T22:32:38.049+0000] {subprocess.py:93} INFO - 	found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-21T22:32:38.148+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2024-08-21T22:32:38.194+0000] {subprocess.py:93} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2024-08-21T22:32:38.217+0000] {subprocess.py:93} INFO - 	found org.apache.kafka#kafka-clients;3.4.1 in central
[2024-08-21T22:32:38.240+0000] {subprocess.py:93} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2024-08-21T22:32:38.257+0000] {subprocess.py:93} INFO - 	found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2024-08-21T22:32:38.273+0000] {subprocess.py:93} INFO - 	found org.slf4j#slf4j-api;2.0.7 in central
[2024-08-21T22:32:38.295+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2024-08-21T22:32:38.325+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2024-08-21T22:32:38.351+0000] {subprocess.py:93} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2024-08-21T22:32:38.369+0000] {subprocess.py:93} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2024-08-21T22:32:38.381+0000] {subprocess.py:93} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2024-08-21T22:32:38.393+0000] {subprocess.py:93} INFO - 	found org.mongodb.spark#mongo-spark-connector_2.12;10.3.0 in central
[2024-08-21T22:32:42.537+0000] {subprocess.py:93} INFO - 	found org.mongodb#mongodb-driver-sync;4.8.2 in central
[2024-08-21T22:32:42.538+0000] {subprocess.py:93} INFO - 	[4.8.2] org.mongodb#mongodb-driver-sync;[4.8.1,4.8.99)
[2024-08-21T22:32:42.544+0000] {subprocess.py:93} INFO - 	found org.mongodb#bson;4.8.2 in central
[2024-08-21T22:32:42.552+0000] {subprocess.py:93} INFO - 	found org.mongodb#mongodb-driver-core;4.8.2 in central
[2024-08-21T22:32:42.562+0000] {subprocess.py:93} INFO - 	found org.mongodb#bson-record-codec;4.8.2 in central
[2024-08-21T22:32:42.598+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 4657ms :: artifacts dl 21ms
[2024-08-21T22:32:42.599+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2024-08-21T22:32:42.600+0000] {subprocess.py:93} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2024-08-21T22:32:42.600+0000] {subprocess.py:93} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2024-08-21T22:32:42.601+0000] {subprocess.py:93} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2024-08-21T22:32:42.601+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2024-08-21T22:32:42.601+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2024-08-21T22:32:42.602+0000] {subprocess.py:93} INFO - 	org.apache.kafka#kafka-clients;3.4.1 from central in [default]
[2024-08-21T22:32:42.602+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
[2024-08-21T22:32:42.602+0000] {subprocess.py:93} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
[2024-08-21T22:32:42.602+0000] {subprocess.py:93} INFO - 	org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-21T22:32:42.603+0000] {subprocess.py:93} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2024-08-21T22:32:42.603+0000] {subprocess.py:93} INFO - 	org.mongodb#bson;4.8.2 from central in [default]
[2024-08-21T22:32:42.603+0000] {subprocess.py:93} INFO - 	org.mongodb#bson-record-codec;4.8.2 from central in [default]
[2024-08-21T22:32:42.603+0000] {subprocess.py:93} INFO - 	org.mongodb#mongodb-driver-core;4.8.2 from central in [default]
[2024-08-21T22:32:42.604+0000] {subprocess.py:93} INFO - 	org.mongodb#mongodb-driver-sync;4.8.2 from central in [default]
[2024-08-21T22:32:42.604+0000] {subprocess.py:93} INFO - 	org.mongodb.spark#mongo-spark-connector_2.12;10.3.0 from central in [default]
[2024-08-21T22:32:42.604+0000] {subprocess.py:93} INFO - 	org.postgresql#postgresql;42.5.4 from central in [default]
[2024-08-21T22:32:42.604+0000] {subprocess.py:93} INFO - 	org.slf4j#slf4j-api;2.0.7 from central in [default]
[2024-08-21T22:32:42.605+0000] {subprocess.py:93} INFO - 	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
[2024-08-21T22:32:42.605+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-08-21T22:32:42.606+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-08-21T22:32:42.606+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-21T22:32:42.606+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-08-21T22:32:42.607+0000] {subprocess.py:93} INFO - 	|      default     |   18  |   1   |   0   |   0   ||   18  |   0   |
[2024-08-21T22:32:42.607+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-08-21T22:32:42.612+0000] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-85246f7a-ce89-48e6-8695-f3658629f852
[2024-08-21T22:32:42.613+0000] {subprocess.py:93} INFO - 	confs: [default]
[2024-08-21T22:32:42.625+0000] {subprocess.py:93} INFO - 	0 artifacts copied, 18 already retrieved (0kB/12ms)
[2024-08-21T22:32:42.845+0000] {subprocess.py:93} INFO - 24/08/21 19:32:42 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-21T22:32:43.285+0000] {subprocess.py:93} INFO - python3: can't open file '/home/spark/postgres_analysis.py': [Errno 2] No such file or directory
[2024-08-21T22:32:43.298+0000] {subprocess.py:93} INFO - 24/08/21 19:32:43 INFO ShutdownHookManager: Shutdown hook called
[2024-08-21T22:32:43.298+0000] {subprocess.py:93} INFO - 24/08/21 19:32:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-e2657e76-33f8-4441-ae02-ccdd51b9f0bb
[2024-08-21T22:32:43.337+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-21T22:32:43.344+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-21T22:32:43.349+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-21T22:32:43.349+0000] {logging_mixin.py:190} INFO - Task start:2024-08-21 22:32:35.740408+00:00 end:2024-08-21 22:32:43.349375+00:00 duration:7.608967
[2024-08-21T22:32:43.350+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): postgres_analysis> dag:<DAG: docker_spark_tasks> dagrun:<DagRun docker_spark_tasks @ 2024-08-21 22:12:10.549926+00:00: manual__2024-08-21T22:12:10.549926+00:00, state:running, queued_at: 2024-08-21 22:12:10.566226+00:00. externally triggered: True>
[2024-08-21T22:32:43.350+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2024-08-21T22:32:43.350+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=docker_spark_tasks, task_id=postgres_analysis, run_id=manual__2024-08-21T22:12:10.549926+00:00, execution_date=20240821T221210, start_date=20240821T223235, end_date=20240821T223243
[2024-08-21T22:32:43.360+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T22:32:43.360+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task postgres_analysis (Bash command failed. The command returned a non-zero exit code 2.; 784)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-21T22:32:43.391+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-21T22:32:43.401+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T22:32:43.402+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
